export const PIANO_SAMPLES = {
  urls: {
    'A0': 'https://tonejs.github.io/audio/salamander/A0.mp3',
    'C1': 'https://tonejs.github.io/audio/salamander/C1.mp3',
    'D#1': 'https://tonejs.github.io/audio/salamander/Ds1.mp3',
    'F#1': 'https://tonejs.github.io/audio/salamander/Fs1.mp3',
    'A1': 'https://tonejs.github.io/audio/salamander/A1.mp3',
    'C2': 'https://tonejs.github.io/audio/salamander/C2.mp3',
    'D#2': 'https://tonejs.github.io/audio/salamander/Ds2.mp3',
    'F#2': 'https://tonejs.github.io/audio/salamander/Fs2.mp3',
    'A2': 'https://tonejs.github.io/audio/salamander/A2.mp3',
    'C3': 'https://tonejs.github.io/audio/salamander/C3.mp3',
    'D#3': 'https://tonejs.github.io/audio/salamander/Ds3.mp3',
    'F#3': 'https://tonejs.github.io/audio/salamander/Fs3.mp3',
    'A3': 'https://tonejs.github.io/audio/salamander/A3.mp3',
    'C4': 'https://tonejs.github.io/audio/salamander/C4.mp3',
    'D#4': 'https://tonejs.github.io/audio/salamander/Ds4.mp3',
    'F#4': 'https://tonejs.github.io/audio/salamander/Fs4.mp3',
    'A4': 'https://tonejs.github.io/audio/salamander/A4.mp3',
    'C5': 'https://tonejs.github.io/audio/salamander/C5.mp3',
    'D#5': 'https://tonejs.github.io/audio/salamander/Ds5.mp3',
    'F#5': 'https://tonejs.github.io/audio/salamander/Fs5.mp3',
    'A5': 'https://tonejs.github.io/audio/salamander/A5.mp3',
    'C6': 'https://tonejs.github.io/audio/salamander/C6.mp3',
    'D#6': 'https://tonejs.github.io/audio/salamander/Ds6.mp3',
    'F#6': 'https://tonejs.github.io/audio/salamander/Fs6.mp3',
    'A6': 'https://tonejs.github.io/audio/salamander/A6.mp3',
    'C7': 'https://tonejs.github.io/audio/salamander/C7.mp3',
    'D#7': 'https://tonejs.github.io/audio/salamander/Ds7.mp3',
    'F#7': 'https://tonejs.github.io/audio/salamander/Fs7.mp3',
    'A7': 'https://tonejs.github.io/audio/salamander/A7.mp3',
    'C8': 'https://tonejs.github.io/audio/salamander/C8.mp3'
  },
  release: 0.4, // Release más corto para un sonido más preciso
  volume: -8,
  baseUrl: ''
};
